import { CURATED_WORDS, HARD_CURATED_WORDS } from './puzzleConfig';

export const MIN_WORD_LENGTH = 3;
export const MAX_WORD_LENGTH = 7;

/** Family-friendly blocklist — extend as needed */
const BLOCKED_WORDS = new Set([
  'sex',
  'damn',
  'hell',
  'crap',
  'kill',
  'dead',
  'die',
  'drug',
  'hate',
  'war',
  'gun',
  'blood',
  'abuse',
  'racist',
  'nazi',
]);

const ENGLISH_WORDS = new Set(
  [
    ...CURATED_WORDS,
    ...HARD_CURATED_WORDS,
    'apple',
    'about',
    'after',
    'again',
    'animal',
    'around',
    'before',
    'begin',
    'being',
    'below',
    'black',
    'blue',
    'bread',
    'bring',
    'build',
    'carry',
    'catch',
    'chair',
    'child',
    'clean',
    'clear',
    'close',
    'color',
    'could',
    'cover',
    'dance',
    'dream',
    'drink',
    'early',
    'earth',
    'eight',
    'every',
    'field',
    'first',
    'fish',
    'five',
    'floor',
    'found',
    'four',
    'fruit',
    'glass',
    'grass',
    'green',
    'group',
    'grow',
    'happy',
    'heart',
    'horse',
    'house',
    'human',
    'large',
    'learn',
    'light',
    'little',
    'live',
    'love',
    'money',
    'month',
    'mouse',
    'never',
    'night',
    'north',
    'ocean',
    'often',
    'other',
    'paper',
    'party',
    'peace',
    'place',
    'plant',
    'play',
    'point',
    'power',
    'quick',
    'quiet',
    'right',
    'river',
    'round',
    'serve',
    'seven',
    'shape',
    'share',
    'sheep',
    'shine',
    'shirt',
    'short',
    'sight',
    'since',
    'sleep',
    'small',
    'smile',
    'snake',
    'snow',
    'some',
    'sound',
    'south',
    'space',
    'speak',
    'speed',
    'spell',
    'spend',
    'sport',
    'stand',
    'star',
    'start',
    'state',
    'still',
    'stone',
    'store',
    'story',
    'study',
    'sugar',
    'table',
    'thank',
    'their',
    'there',
    'these',
    'thing',
    'think',
    'third',
    'those',
    'three',
    'today',
    'together',
    'train',
    'travel',
    'tree',
    'under',
    'until',
    'voice',
    'walk',
    'water',
    'week',
    'west',
    'whale',
    'where',
    'white',
    'whole',
    'wind',
    'world',
    'write',
    'year',
    'young',
    'zebra',
  ].map((w) => w.toLowerCase())
);

export const normalizeWord = (word: string): string => word.trim().toLowerCase();

export const isValidPuzzleWord = (word: string): boolean => {
  const w = normalizeWord(word);
  if (!/^[a-z]+$/.test(w)) return false;
  if (w.length < MIN_WORD_LENGTH || w.length > MAX_WORD_LENGTH) return false;
  if (BLOCKED_WORDS.has(w)) return false;
  if (!/[aeiouy]/.test(w)) return false;
  return ENGLISH_WORDS.has(w);
};

export const wordValidationMessage = (word: string): string | null => {
  const w = normalizeWord(word);
  if (!/^[a-z]+$/.test(w)) return 'Letters only, no spaces or numbers';
  if (w.length < MIN_WORD_LENGTH || w.length > MAX_WORD_LENGTH) {
    return `Use ${MIN_WORD_LENGTH}–${MAX_WORD_LENGTH} letters`;
  }
  if (BLOCKED_WORDS.has(w)) return 'That word is not allowed';
  if (!/[aeiouy]/.test(w)) return 'Must be a real English word';
  if (!ENGLISH_WORDS.has(w)) return 'Not recognized — try a common English word';
  return null;
};
